---
title: "05_timeOfDay_OAD_weekend"
format: html
editor: visual
---

```{r}
#| label: initalize
#| include: false

library(tidyverse)
library(emmeans)

eval <- FALSE # set this to FALSE to run nothing
```

# Analysis function

Notes: includes time of day, adds OAD/weekend interaction

```{r, eval = eval}
#| label: analysis

regions <- c('arr', 'dfw', 'elp', 'hgb', 'san')
wknd <- c('Saturday', 'Sunday')

analysis <- lapply(regions, function(region){

  # Read data
  df <- readRDS(paste0('../data/dfs_timeOfDay/',region)) |> 
    mutate(IsWeekend = if_else(Weekday %in% wknd, 1, 0) |> as.factor())
  
  # Model equation
  eqn_quasi <- TrafficCount ~ TrafficType + Station + TimeOfDay + # traffic info
    IsOAD + AQI_Cat + # aqi
    IsOAD:IsWeekend + # weekday no longer included
    IsWeekend + Holiday +  Month + Year + # datetime
    MeanT + Precip + Sunshine_Hrs + RelativeH + WindSpeed + WMO + # weather
    IsOAD:TimeOfDay + IsOAD:TrafficType + #IsOAD:AQI_Cat removed 
    TimeOfDay:TrafficType + TimeOfDay:AQI_Cat + TrafficType:AQI_Cat + # other ints
    offset(log(Hours)) # adding offset
  
  # Fit model
  model_quasi <- glm(eqn_quasi, family = quasipoisson, data = df) 
  
  # Estimate coefficents
  sum <- summary.glm(model_quasi) |> coef()
  
  # Get all params in the model
  all_params <- names(coef(model_quasi)) 
  
  # Define parameters of interest (may not be present for all regions)
  param_list <- c("IsOAD1", 
                  "IsWeekend1",
                  "IsOAD1:IsWeekend1",
                  "TrafficTypePed", 
                  "TrafficTypePed:IsOAD1",
                  "AQI_CatModerate", 
                  "AQI_CatUnhealthy for Sensitive Groups",
                  "AQI_CatUnhealthy", 
                  "AQI_CatVery Unhealthy",
                  "TrafficTypePed:AQI_CatModerate", 
                  "TrafficTypePed:AQI_CatUnhealthy for Sensitive Groups",
                  "TrafficTypePed:AQI_CatUnhealthy",
                  "TrafficTypePed:AQI_CatVery Unhealthy")
    
  # Figure out which are present in this model
  select_params <- param_list[param_list %in% all_params] 
  
  # Get confidience interval
  conf <- confint(model_quasi, parm = select_params)
  
  # Save results
  filePath <- paste0("../results/05_timeOfDay_OAD_weekend/",region,"_param_ci.csv")
  write.csv(conf, filePath)
  
  filePath <- paste0("../results/05_timeOfDay_OAD_weekend/",region,"_model_summary.csv")
  write.csv(sum, filePath)
})
```
