---
title: "FigureS4_S8"
format: html
editor: visual
---

```{r}
#| label: init
#| include: false

library(osmdata)
library(tidyverse)
library(ggplot2)
library(ggrepel)
library(sf)

replot <- FALSE # set to TRUE to actually rerender
save_figures <- TRUE
```

# Plotting function

```{r}
#| label: plotting_function

plot_it <- function(region, retrieve_osm = FALSE){
          
  # Get region name
  labels <- list("arr" = "Austin-Round Rock",
                 "bpa" = "Beaumont-Port Arthur",
                 "cc" = "Corpus Christi",
                 "dfw" = "Dallas-Fort Worth",
                 "elp" = "El Paso",
                 "hgb" = "Houston-Galveston-Brazoria",
                 "netx" = "Northeast Texas",
                 "san" = "San Antonio",
                 "vic" = "Victoria")
  region_name <- labels[[region]]
  
  # Only get stations actually used in the analysis
  stations_used <- readRDS(paste0("../data/dfs_timeOfDay/",region)) |> 
    pull(Station) |> unique()
  
  # Get station location data
  path <- '../data/traffic_station_locations_with_OAD.csv'
  df <- read.csv(path) |> 
    filter(OAD == region, ) |> 
    dplyr::select(station_id_tmg, count_type, longitude, latitude) |> 
    rename(Long = longitude,
           Lat = latitude,
           Station = station_id_tmg,
           CountType = count_type) |> 
    filter(Station %in% stations_used) |> 
    group_by(Station) |> 
    mutate(`Count Type` = case_when(all(CountType == "Bicycles only") ~ "Bicycles only",
                                   all(CountType == "Pedestrians only") ~ "Pedestrians only",
                                   TRUE ~ "Bicycles and Pedestrians")) |> 
    dplyr::select(Station, Long, Lat, `Count Type`) |> 
    unique() |> 
    st_as_sf(coords = c("Long", "Lat"), crs = 4326)
  
  # Define bbox with some small padding
  bbox <- st_bbox(df)
  pad <- rep(c(-0.05, 0.05), each = 2) # approx 5km
  bbox <- pad + bbox
  
  if (retrieve_osm){
    
    # Make a bbox greater than the bbox so everything is captured 
    bbox_larger <- bbox + rep(c(-0.2, 0.2), each = 2) # approx 20km
    
    # PARKS
    parks <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "leisure", value = "park") |>
      osmdata_sf()
    saveRDS(parks, paste0("../data-raw/osm/parks_",region,".rds"))
    
     # LEISURE
    leisure <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "leisure") |>
      osmdata_sf()
    saveRDS(leisure, paste0("../data-raw/osm/leisure_",region,".rds"))
    
    # MOTORWAY
    motorway <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "highway",
                      value = c("motorway")) |>
      osmdata_sf()
    saveRDS(motorway, paste0("../data-raw/osm/motorway_",region,".rds"))
    
    # TRUNK
    trunk <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "highway",
                      value = c("trunk")) |>
      osmdata_sf()
    saveRDS(trunk, paste0("../data-raw/osm/trunk_",region,".rds"))
    
    # PRIMARY
    primary <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "highway",
                      value = c("primary")) |>
      osmdata_sf()
    saveRDS(primary, paste0("../data-raw/osm/primary_",region,".rds"))
    
    # SECONDARY
    secondary <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "highway",
                      value = c("secondary")) |>
      osmdata_sf()
    saveRDS(secondary, paste0("../data-raw/osm/secondary_",region,".rds"))
    
    # TERTIARY
    tertiary <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "highway",
                      value = c("tertiary")) |> 
      osmdata_sf()
    saveRDS(tertiary, paste0("../data-raw/osm/tertiary_",region,".rds"))
    
    # PLACE 
    place <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "place",
                      value = c("city", "town", "neighbourhood", "suburb")) |>
      osmdata_sf()
    saveRDS(place, paste0("../data-raw/osm/place_",region,".rds"))
    
    # WATER
    water <- opq(bbox = bbox_larger) |>
      add_osm_feature(key = "natural", value = "water") |>
      osmdata_sf()
    saveRDS(water, paste0("../data-raw/osm/water_",region,".rds"))
  }

  # Read osm files
  parks <- readRDS(paste0("../data-raw/osm/parks_",region,".rds"))
  leisure <- readRDS(paste0("../data-raw/osm/leisure_",region,".rds"))
  motorway <- readRDS(paste0("../data-raw/osm/motorway_",region,".rds"))
  trunk <- readRDS(paste0("../data-raw/osm/trunk_",region,".rds"))
  primary <- readRDS(paste0("../data-raw/osm/primary_",region,".rds"))
  secondary <- readRDS(paste0("../data-raw/osm/secondary_",region,".rds"))
  tertiary <- readRDS(paste0("../data-raw/osm/tertiary_",region,".rds"))
  place <- readRDS(paste0("../data-raw/osm/place_",region,".rds"))
  water <- readRDS(paste0("../data-raw/osm/water_",region,".rds"))
  
  # Get specific place info
  places <- place$osm_multipolygons
  
  # City boundary
  city_centroids <- place$osm_points |> 
    filter(place == "city") |> 
    group_by(name) |> 
    summarise(Center = st_centroid(geometry))
  
  # Combine polygons and multipolygons for OSM feature plotting
  leisures <- list(leisure$osm_multipolygons, leisure$osm_polygons) |> 
    bind_rows()
  waters <- list(water$osm_multipolygons, water$osm_polygons) |> 
    bind_rows()
  
  # Now plotting
  p <- ggplot() + 
    geom_sf(data = leisures, aes(fill = "Leisure"), color = "#d0ecb4") + 
    geom_sf(data = waters, aes(fill = "Water"), color = "#abd4e0") + 
    geom_sf(data = tertiary$osm_lines, fill = 'grey90', color = 'grey90') +
    geom_sf(data = secondary$osm_lines, fill = 'grey80', color = 'grey80') +
    geom_sf(data = primary$osm_lines, fill = 'grey70', color = 'grey70') +
    geom_sf(data = trunk$osm_lines, fill = 'grey60', color = 'grey60') +
    geom_sf(data = motorway$osm_lines, fill = 'grey50', color = 'grey50') + 
    geom_sf(data = df, 
            aes(shape = `Count Type`), 
            color = 'white', 
            fill = '#BF5700',
            size = 2,
            alpha = 1) + 
    coord_sf(xlim = bbox[c(1,3)], ylim = bbox[c(2,4)]) + 
    geom_text_repel(data = city_centroids, 
                aes(label = name, geometry = Center),
                stat = "sf_coordinates",
                max.overlaps = 5,
                size = 2.5,
                bg.color = alpha("white", 0.5),
                alpha = 1) + 
    scale_fill_manual(name = "OSM Feature", 
                      values = c("Water" = "#abd4e0", 
                                 "Leisure" = "#d0ecb4")) + 
    scale_shape_manual(name = 'Count Type',
                       values = c('Bicycles only' = 21,
                                  'Bicycles and Pedestrians' = 22,
                                  'Pedestrians only' = 24)) +
    theme_void() + 
    theme(plot.title = element_text(hjust = 0.5))
  
  return(p)
}
```

# Plots

```{r, eval = replot}

a <- plot_it('arr')
d <- plot_it('dfw')
e <- plot_it('elp')
h <- plot_it('hgb')
s <- plot_it('san')

if (save_figures){
  ggsave('../figures/fig_s7.pdf', plot = a, width = 15, height = 10, units = 'cm')
  ggsave('../figures/fig_s8.pdf', plot = d, width = 15, height = 10, units = 'cm')
  ggsave('../figures/fig_s9.pdf', plot = e, width = 15, height = 10, units = 'cm')
  ggsave('../figures/fig_s10.pdf', plot = h, width = 15, height = 6, units = 'cm') # smaller bc weird dims
  ggsave('../figures/fig_s11.pdf', plot = s, width = 15, height = 10, units = 'cm')
}
```
